erver.port: 8080

eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/

spring.datasource.url: jdbc:mysql://mysql/review-db

spring.rabbitmq.host: rabbitmq

spring.cloud.stream.kafka.binder.brokers: kafka
app.eureka-server: eureka
